name: CI

permissions:
  contents: write
  
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: 
  push:

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:


    buildDebug:
        name: Debug build
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Run debug build
                run: |
                  gradle wrapper --gradle-version 7.4.1
                  ./gradlew assembleDebug

            -   name: Upload artifact to GitHub
                uses: actions/upload-artifact@v6
                with:
                    name: storage-usb-debug.apk
                    path: ./app/build/outputs/apk/debug/app-debug.apk
